package com.loom.core.network.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NetworkEventCreateRequest(
    val title: String,
    val description: String? = null,
    @SerialName("start_time") val startTime: String,
    @SerialName("end_time") val endTime: String? = null,
    @SerialName("location_name") val locationName: String? = null,
    @SerialName("location_address") val locationAddress: String? = null,
    @SerialName("asset_ids") val assetIds: List<String> = emptyList(),
    @SerialName("thumbnail_id") val thumbnailId: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val category: String? = null,
    @SerialName("max_attendees") val maxAttendees: Int? = null,
    @SerialName("is_online") val isOnline: Boolean? = null,
    @SerialName("is_public") val isPublic: Boolean? = null,
    @SerialName("requires_payment") val requiresPayment: Boolean? = null,
    @SerialName("price_amount") val priceAmount: String? = null,
    @SerialName("price_currency") val priceCurrency: String? = null,
    @SerialName("stripe_price_id") val stripePriceId: String? = null,
    @SerialName("payment_methods_allowed") val paymentMethodsAllowed: List<String>? = null,
    val requirements: List<String>? = null,
    @SerialName("secure_attendance_token") val secureAttendanceToken: String? = null,
    @SerialName("support_email") val supportEmail: String? = null,
    @SerialName("support_url") val supportUrl: String? = null,
    @SerialName("website_url") val websiteUrl: String? = null,
    @SerialName("whatsapp_url") val whatsappUrl: String? = null,
    @SerialName("telegram_url") val telegramUrl: String? = null,
    @SerialName("discord_url") val discordUrl: String? = null,
    @SerialName("zoom_url") val zoomUrl: String? = null,
    val timezone: String? = null,
    @SerialName("requires_qr_checkin") val requiresQrCheckin: Boolean? = null,
    @SerialName("meeting_instructions") val meetingInstructions: String? = null,
    @SerialName("live_stream_url") val liveStreamUrl: String? = null,
    @SerialName("is_free") val isFree: Boolean? = null,
    val status: String? = null,
    val tags: List<String>? = null
)

@Serializable
data class NetworkEventCreateResponse(
    val id: String,
    val creator: String,
    @SerialName("creator_display_name") val creatorDisplayName: String,
    val title: String,
    val description: String? = null,
    @SerialName("start_time") val startTime: String,
    @SerialName("end_time") val endTime: String? = null,
    @SerialName("location_name") val locationName: String? = null,
    @SerialName("location_address") val locationAddress: String? = null,
    val assets: List<NetworkPostMedia> = emptyList(),
    @SerialName("thumbnail_url") val thumbnailUrl: String? = null,
    @SerialName("read_latitude") val latitude: Double? = null,
    @SerialName("read_longitude") val longitude: Double? = null,
    val category: String? = null,
    @SerialName("max_attendees") val maxAttendees: Int? = null,
    @SerialName("is_online") val isOnline: Boolean = false,
    @SerialName("is_public") val isPublic: Boolean = true,
    @SerialName("requires_payment") val requiresPayment: Boolean = false,
    @SerialName("price_amount") val priceAmount: String? = null,
    @SerialName("price_currency") val priceCurrency: String? = null,
    @SerialName("stripe_price_id") val stripePriceId: String? = null,
    @SerialName("payment_methods_allowed") val paymentMethodsAllowed: List<String> = emptyList(),
    val requirements: List<String> = emptyList(),
    @SerialName("secure_attendance_token") val secureAttendanceToken: String? = null,
    @SerialName("support_email") val supportEmail: String? = null,
    @SerialName("support_url") val supportUrl: String? = null,
    @SerialName("website_url") val websiteUrl: String? = null,
    @SerialName("whatsapp_url") val whatsappUrl: String? = null,
    @SerialName("telegram_url") val telegramUrl: String? = null,
    @SerialName("discord_url") val discordUrl: String? = null,
    @SerialName("zoom_url") val zoomUrl: String? = null,
    val timezone: String? = null,
    @SerialName("requires_qr_checkin") val requiresQrCheckin: Boolean = false,
    @SerialName("meeting_instructions") val meetingInstructions: String? = null,
    @SerialName("live_stream_url") val liveStreamUrl: String? = null,
    @SerialName("is_free") val isFree: Boolean = true,
    @SerialName("is_cancelled") val isCancelled: Boolean = false,
    val status: String? = null,
    val tags: List<String> = emptyList(),
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String
)
